export const permissions = [
    "VIEW_DASHBOARD",
    "MANAGE_USERS",
    "CREATE_POST",
    "EDIT_POST",
    "DELETE_POST",
    "MANAGE_SETTINGS",
    "VIEW_ANALYTICS",
    "MANAGE_ROLES",
    "APPROVE_COMMENTS",
    "ACCESS_API",
    "EXPORT_DATA",
    "IMPORT_DATA",
    "MANAGE_MEDIA",
    "VIEW_REPORTS",
    "SEND_NOTIFICATIONS"
]